# @Author: Deep Shah
# @Email: shahdeep966@gmail.com
# @website: http://deepshah.linkpc.net
# @Organization: Engineering Services International
# @Date:   2025-10-31 15:04:39
# @Last Modified by:   Deep Shah
# @Last Modified time: 2025-10-31 15:05:23

packages:
  - '01-project'
  - '02-project'
  - '01-folder'
